# Root level config file stuff
## Import files (Colors, Fonts, Etc)
import = [
  # Middle-of-the-road themes
  "~/.config/alacritty/alacritty-theme/themes/gnome_terminal.toml"
  # "~/.config/alacritty/alacritty-theme/themes/konsole_linux.toml"
  # "~/.config/alacritty/alacritty-theme/themes/tomorrow_night.toml"
  # "~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"
  # "~/.config/alacritty/alacritty-theme/themes/breeze.toml"

  # Bright themes
  # "~/.config/alacritty/alacritty-theme/themes/chicago95.toml"
  # "~/.config/alacritty/alacritty-theme/themes/tomorrow_night_bright.toml"
  # "~/.config/alacritty/alacritty-theme/themes/xterm.toml"
  # "~/.config/alacritty/alacritty-theme/themes/terminal_app.toml"
  # "~/.config/alacritty/alacritty-theme/themes/hyper.toml"
  # "~/.config/alacritty/alacritty-theme/themes/monokai_charcoal.toml"

  # Themes with odd background colours
  # "~/.config/alacritty/alacritty-theme/themes/github_dark.toml"
  # "~/.config/alacritty/alacritty-theme/themes/iris.toml"
  # "~/.config/alacritty/alacritty-theme/themes/marine_dark.toml"
  # "~/.config/alacritty/alacritty-theme/themes/Cobalt2.toml"

  # Themes with too little constast between colours
  # "~/.config/alacritty/alacritty-theme/themes/google.toml"

  # Cool themes
  # "~/.config/alacritty/alacritty-theme/themes/inferno.toml"
]

live_config_reload = true
# shell = "" | { program = "", args = ["", ] }

[env]
# Fixes htop over ssh
TERM = "xterm-256color"

## Terminal window settings
[window]
dimensions = { columns = 130, lines = 32 }
padding = { x = 10, y = 10 }
# dynamic_padding = true
decorations = "full"
opacity = 1.0
startup_mode = "Windowed"
dynamic_title = true
resize_increments = true

[font]
# size = 9.5
size = 12
# size = 13
# builtin_box_drawing = true

# Fonts shouldn't end with "Mono" for NVChad ----------------------------------
# Good (with bold, italic & bold italic)
# normal      = { family = "Inconsolata Nerd Font", style = "Regular" }
# bold        = { family = "Inconsolata Nerd Font", style = "Bold" }
# italic      = { family = "Inconsolata Nerd Font", style = "Italic" }
# bold_italic = { family = "Inconsolata Nerd Font", style = "Bold Italic" }

# normal      = { family = "Code New Roman Nerd Font", style = "Regular" }
# bold        = { family = "Code New Roman Nerd Font", style = "Bold" }
# italic      = { family = "Code New Roman Nerd Font", style = "Italic" }
# bold_italic = { family = "Code New Roman Nerd Font", style = "Bold Italic" }

# Original terminess font
# normal      = { family = "Terminess Nerd Font", style = "Regular" }
# bold        = { family = "Terminess Nerd Font", style = "Bold" }
# italic      = { family = "Terminess Nerd Font", style = "Italic" }
# bold_italic = { family = "Terminess Nerd Font", style = "Bold Italic" }

# Terminess font with emojis :)
normal      = { family = "emojified_nerd_font", style = "Regular" }
bold        = { family = "emojified_nerd_font", style = "Bold" }
italic      = { family = "emojified_nerd_font", style = "Italic" }
bold_italic = { family = "emojified_nerd_font", style = "Bold Italic" }

# Good (but no bold or italic)
# GohuFont 14

# Ok (no bold or italic)

# Mid
# BigBlueTerm437
# ProFont IIx
# BitstromWera

# Bad formatting
# Proggy

[colors]
transparent_background_colors = true
# draw_bold_text_with_bright_colors = true

[bell]
animation = "EaseOutSine"
# command = ""
# command = { program = "", args = ["", ] }

## Cursor
[cursor]
[cursor.style]
shape = "Block"
blinking = "On"
# unfocused_hollow = true

[scrolling]
# history = 100000

[hints]
# ???

[debug]
# renderer = "glsl3"
# highlight_damage = true
# log_level = "Info"
prefer_egl = true
