# TODO uncomment for newer alacritty versions vv
# [general]
import = [
  # Solid choices
  "~/.config/alacritty/alacritty-theme/themes/gnome_terminal.toml"
  # "~/.config/alacritty/alacritty-theme/themes/konsole_linux.toml"
  # "~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"
  # "~/.config/alacritty/alacritty-theme/themes/breeze.toml"

  # Bright themes
  # "~/.config/alacritty/alacritty-theme/themes/chicago95.toml"
  # "~/.config/alacritty/alacritty-theme/themes/tomorrow_night_bright.toml"
  # "~/.config/alacritty/alacritty-theme/themes/xterm.toml"
  # "~/.config/alacritty/alacritty-theme/themes/terminal_app.toml"
  # "~/.config/alacritty/alacritty-theme/themes/hyper.toml"
  # "~/.config/alacritty/alacritty-theme/themes/monokai_charcoal.toml"

  # Themes with odd background colours
  # "~/.config/alacritty/alacritty-theme/themes/github_dark.toml"
  # "~/.config/alacritty/alacritty-theme/themes/iris.toml"
  # "~/.config/alacritty/alacritty-theme/themes/marine_dark.toml"
  # "~/.config/alacritty/alacritty-theme/themes/Cobalt2.toml"
  # "~/.config/alacritty/alacritty-theme/themes/ubuntu.toml"
  # "~/.config/alacritty/alacritty-theme/themes/synthwave_84.toml"

  # Themes with too little constast between colours
  # "~/.config/alacritty/alacritty-theme/themes/google.toml"
  # "~/.config/alacritty/alacritty-theme/themes/gruvbox_material.toml"
  # "~/.config/alacritty/alacritty-theme/themes/vesper.toml"
  # "~/.config/alacritty/alacritty-theme/themes/tokyo_night_enhanced.toml"
  # "~/.config/alacritty/alacritty-theme/themes/monokai.toml"
  # "~/.config/alacritty/alacritty-theme/themes/gruvbox_material_medium_dark.toml"
  # "~/.config/alacritty/alacritty-theme/themes/ayu_dark.toml"

  # Themes that look a little washed out
  # "~/.config/alacritty/alacritty-theme/themes/terafox.toml"

  # Themes where text is straight up unreadable
  # "~/.config/alacritty/alacritty-theme/themes/tomorrow_night.toml"

  # Cool themes
  # "~/.config/alacritty/alacritty-theme/themes/inferno.toml"
  # "~/.config/alacritty/alacritty-theme/themes/bluish.toml"

  # Uncategorised
]

live_config_reload = true

[env]
# Fixes htop over ssh
TERM = "xterm-256color"

## Terminal window settings
[window]
dimensions = { columns = 130, lines = 32 }
padding = { x = 10, y = 10 }
# dynamic_padding = true
decorations = "full"
opacity = 0.90
startup_mode = "Windowed"
dynamic_title = true
resize_increments = true
blur = true

[font]
size = 12

# bold, italic & bold_italic font variants
# automatically use the normal font family as a fallback

# good
normal = { family = "emojified_nerd_font"}
# normal = { family = "Code New Roman Nerd Font"}
# normal = { family = "Inconsolata Nerd Font"}

# good w/ caveats
# normal = { family = "GohuFont 14 Nerd Font"} # no bold / italic

# meh
# normal = { family = "DepartureMono Nerd Font"}
# normal = { family = "BigBlueTerm437 Nerd Font"}
# normal = { family = "ProFont IIx"}
# normal = { family = "Bitstrom Wera"}
# normal = { family = "Hurmit Nerd Font"}

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[bell]
animation = "EaseOutSine"

## Cursor
[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "On"

[scrolling]
history = 100000

[hints]
# ???

[debug]
# renderer = "glsl3"
# highlight_damage = true
# log_level = "Info"
prefer_egl = true
